"""gate_run34 (HEAD a17aed7) follow-ups, python only:

1. verify_symbolspec compared the frozen broker_spec ``name`` to the
   export's NESTED ``symbol`` object, so it could never match.
2. S8-SPEC-3 custom-symbol identity: a custom export's name is EXACT_MATCH
   only if it is the gate-declared tester symbol of an in-scope gold AND
   its path starts with ``Custom\\Mql5Bot\\gold\\``.
3. S8-SPEC-3 custom-symbol tick_value_profit: a readback of 0 is
   DERIVED_EXACT_MATCH only if BOTH same-run witnesses equal the frozen
   value (import record readback; tick_size*contract_size and the leg
   .ini deposit Currency). Anything missing or unequal -> DECISION_CHANGING.
5. compile_metadata TERMINAL_BUILD from the same-run export, source named.
6. S8-ANCHOR-REL-1: a recorded source commit != anchor is accepted only as
   DESCENDANT_FROZEN_BYTES_IDENTICAL, recomputed by the verifier from git.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

import pytest
from mql5bot import gate_selfcheck as gs
from mql5bot import owner_gate as og
from mql5bot import stage8_package as s8p

REPO = Path(__file__).resolve().parents[1]
FROZEN_SPEC = json.loads((REPO / "artifacts/gold/manifest.json")
                         .read_text())["broker_spec"]
G2_PATH = "Custom\\Mql5Bot\\gold\\EURUSD.G2"

BASE_EXPORT = {
    "schema": "mql5bot.broker_export/1", "server": "MetaQuotes-Demo",
    "broker": "MetaQuotes Ltd.", "point": 1e-05, "tick_size": 1e-05,
    "tick_value_profit": 1.0, "contract_size": 100000.0,
    "volume_min": 0.01, "volume_max": 100.0, "volume_step": 0.01,
    "volume_limit": 0.0, "stops_level_points": 0, "freeze_level_points": 0,
    "trade_mode": 4, "filling_mode_mask": 1, "expiration_mode_mask": 15,
    "currency_profit": "USD", "timestamp": "2026-10-05T08:00:00Z",
    "terminal_build": 5430, "spread_points": 0, "spread_float": True,
    "custom_symbol": False, "custom_fixed_spread_points": None,
    "symbol": {"name": "EURUSD", "path": "Forex\\EURUSD"},
}
CUSTOM_EXPORT = dict(BASE_EXPORT, custom_symbol=True, tick_value_profit=0.0,
                     symbol={"name": "EURUSD.G2", "path": G2_PATH})


def _import_record(readback="1.0000000000", ok=True):
    return {"ok": True, "symbol": "EURUSD.G2", "verified_properties": [
        {"enum": "SYMBOL_TRADE_CONTRACT_SIZE", "expected": "100000.0000000000",
         "ok": True, "readback": "100000.0000000000"},
        {"enum": "SYMBOL_TRADE_TICK_VALUE", "expected": "1.0000000000",
         "ok": ok, "readback": readback}]}


def _ini(currency="USD"):
    return ("; generated by mql5bot.mt5tester\n[Tester]\n"
            "Expert=Mql5Bot\\Mql5Bot.ex5\nSymbol=EURUSD.G2\nPeriod=M1\n"
            f"Deposit=10000.00\nCurrency={currency}\nLeverage=100\n"
            "\n[TesterInputs]\nInpBaseGateWeight=1.0\n")


def _pkg(tmp_path, export, record=None, inis=None, bind=True):
    root = tmp_path / "pkg"
    (root / "symbolspec").mkdir(parents=True)
    (root / og.LAYOUT["symbolspec"]).write_text(json.dumps(export))
    if record is not None:
        (root / og.symbolspec_import_rel("gold2")).write_text(
            json.dumps(record))
    for model, text in (inis or {}).items():
        p = root / og.tester_ini_rel("gold2", model)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    if bind:
        arts = {str(p.relative_to(root)).replace("\\", "/"):
                hashlib.sha256(p.read_bytes()).hexdigest()
                for p in sorted(root.rglob("*")) if p.is_file()}
        (root / og.LAYOUT["archive_manifest"]).write_text(
            json.dumps({"artifacts": arts}))
    return root


def _witnessed(tmp_path, export=CUSTOM_EXPORT, **kw):
    record = kw.pop("record", _import_record())
    inis = kw.pop("inis", {"m1_ohlc": _ini(), "every_tick": _ini()})
    return _pkg(tmp_path, export, record, inis, **kw)


# ------------------------------------------------- 1. nested symbol name

def test_nested_symbol_name_is_compared_not_the_object(tmp_path):
    rep = og.verify_symbolspec(_pkg(tmp_path, BASE_EXPORT), FROZEN_SPEC)
    assert rep["field_classes"]["name"] == og.EXACT_MATCH
    assert rep["state"] == og.VALID, rep["reasons"]
    assert rep["identity"]["symbol"] == "EURUSD"


def test_flat_symbol_string_is_accepted_too(tmp_path):
    rep = og.verify_symbolspec(
        _pkg(tmp_path, dict(BASE_EXPORT, symbol="EURUSD")), FROZEN_SPEC)
    assert rep["field_classes"]["name"] == og.EXACT_MATCH


def test_wrong_nested_name_is_still_decision_changing(tmp_path):
    rep = og.verify_symbolspec(
        _pkg(tmp_path, dict(BASE_EXPORT, symbol={"name": "GBPUSD"})),
        FROZEN_SPEC)
    assert rep["field_classes"]["name"] == og.DECISION_CHANGING_MISMATCH
    assert rep["state"] == og.MISMATCHED


# ------------------------------------- 2. S8-SPEC-3 custom-symbol identity

def test_custom_identity_exact_only_for_declared_symbol_and_path(tmp_path):
    rep = og.verify_symbolspec(_witnessed(tmp_path), FROZEN_SPEC, ["gold2"])
    assert rep["field_classes"]["name"] == og.EXACT_MATCH
    basis = rep["field_bases"]["name"]
    assert basis["gold"] == "gold2"
    assert basis["name_is_declared_tester_symbol"] is True
    assert basis["path_prefix_ok"] is True
    assert basis["declared_tester_symbols"] == {"gold2": "EURUSD.G2"}


@pytest.mark.parametrize("symbol, scope", [
    ({"name": "EURUSD.G2", "path": "Custom\\Other\\EURUSD.G2"}, ["gold2"]),
    ({"name": "EURUSD.G2"}, ["gold2"]),                       # no path
    ({"name": "EURUSD.G1", "path": "Custom\\Mql5Bot\\gold\\EURUSD.G1"},
     ["gold2"]),                                              # other gold
    ({"name": "EURUSD.G9", "path": "Custom\\Mql5Bot\\gold\\EURUSD.G9"},
     ["gold1", "gold2"]),                                     # undeclared
    ({"name": "EURUSD", "path": "Custom\\Mql5Bot\\gold\\EURUSD"},
     ["gold2"]),                                              # frozen name
])
def test_custom_identity_otherwise_decision_changing(tmp_path, symbol, scope):
    rep = og.verify_symbolspec(
        _witnessed(tmp_path, dict(CUSTOM_EXPORT, symbol=symbol)),
        FROZEN_SPEC, scope)
    assert rep["field_classes"]["name"] == og.DECISION_CHANGING_MISMATCH
    assert rep["state"] == og.MISMATCHED


# ------------------------- 3. S8-SPEC-3 custom-symbol tick_value_profit

def test_tick_value_zero_with_both_witnesses_is_derived_exact(tmp_path):
    rep = og.verify_symbolspec(_witnessed(tmp_path), FROZEN_SPEC, ["gold2"])
    assert rep["field_classes"]["tick_value_profit"] == \
        og.DERIVED_EXACT_MATCH
    assert rep["state"] == og.VALID, rep["reasons"]
    basis = rep["field_bases"]["tick_value_profit"]
    assert basis["reasons"] == []
    assert basis["witness_a"] == {"file": "symbolspec/import_gold2.json",
                                  "readback": "1.0000000000", "ok": True}
    assert basis["witness_b"]["product"] == 1.0
    assert basis["witness_b"]["deposit_currency"] == {
        "tester/gold2_every_tick.ini": "USD",
        "tester/gold2_m1_ohlc.ini": "USD"}


def _tv(rep):
    return (rep["field_classes"]["tick_value_profit"], rep["state"],
            " | ".join(rep["field_bases"]["tick_value_profit"]["reasons"]))


def test_negative_import_readback_0_9(tmp_path):
    cls, state, why = _tv(og.verify_symbolspec(
        _witnessed(tmp_path, record=_import_record("0.9000000000")),
        FROZEN_SPEC, ["gold2"]))
    assert (cls, state) == (og.DECISION_CHANGING_MISMATCH, og.MISMATCHED)
    assert "readback '0.9000000000' != frozen 1.0" in why


def test_negative_deposit_eur(tmp_path):
    cls, state, why = _tv(og.verify_symbolspec(
        _witnessed(tmp_path, inis={"m1_ohlc": _ini(),
                                   "every_tick": _ini("EUR")}),
        FROZEN_SPEC, ["gold2"]))
    assert (cls, state) == (og.DECISION_CHANGING_MISMATCH, og.MISMATCHED)
    assert "deposit Currency 'EUR' != currency_profit 'USD'" in why


def test_negative_import_record_missing(tmp_path):
    cls, state, why = _tv(og.verify_symbolspec(
        _witnessed(tmp_path, record=None), FROZEN_SPEC, ["gold2"]))
    assert (cls, state) == (og.DECISION_CHANGING_MISMATCH, og.MISMATCHED)
    assert "symbolspec/import_gold2.json missing from the package" in why


@pytest.mark.parametrize("case", ["unbound", "ok_false", "no_ini",
                                  "export_nonzero", "product", "tampered"])
def test_negative_other_witness_failures(tmp_path, case):
    kw: dict = {}
    export = CUSTOM_EXPORT
    if case == "unbound":
        kw["bind"] = False
    elif case == "ok_false":
        kw["record"] = _import_record(ok=False)
    elif case == "no_ini":
        kw["inis"] = {}
    elif case == "export_nonzero":
        export = dict(CUSTOM_EXPORT, tick_value_profit=0.5)
    elif case == "product":
        export = dict(CUSTOM_EXPORT, contract_size=10000.0)
    root = _witnessed(tmp_path, export, **kw)
    if case == "tampered":   # bytes changed after binding
        (root / og.symbolspec_import_rel("gold2")).write_text(
            json.dumps(_import_record()) + " ")
    rep = og.verify_symbolspec(root, FROZEN_SPEC, ["gold2"])
    assert rep["field_classes"]["tick_value_profit"] == \
        og.DECISION_CHANGING_MISMATCH
    assert rep["state"] == og.MISMATCHED


def test_non_custom_zero_tick_value_is_unchanged(tmp_path):
    rep = og.verify_symbolspec(
        _witnessed(tmp_path, dict(BASE_EXPORT, tick_value_profit=0.0)),
        FROZEN_SPEC, ["gold2"])
    assert rep["field_classes"]["tick_value_profit"] == \
        og.DECISION_CHANGING_MISMATCH
    assert "tick_value_profit" not in rep["field_bases"]


# ------------------------------------- package builder (items 3, 4, 5)

def test_package_carries_witnesses_terminal_build_and_fixed_spread(
        tmp_path):
    from tests.test_stage8_package_from_gate import _build

    custom = dict(CUSTOM_EXPORT, spread_float=False,
                  custom_fixed_spread_points=1, terminal_build=5430)
    custom_file = tmp_path / "symbolspec_EURUSD.G2.json"
    custom_file.write_text(json.dumps(custom), encoding="utf-8")
    _, pkg, ev = _build(tmp_path, BASE_EXPORT,
                        symbolspec_custom={"gold2": custom_file})
    # the gate evidence names (owner_gate.ps1 stage 4 / stage 5)
    (ev / "import_EURUSD.G2.json").write_text(json.dumps(_import_record()))
    for m in ("m1_ohlc", "every_tick"):
        (ev / f"tester_gold2_{m}.ini").write_text(_ini())
    rec = s8p.build_package(repo=REPO, package=pkg, gate_evidence=ev,
                            data_folder=tmp_path / "data", golds=["gold2"],
                            symbolspec_export=tmp_path / "EURUSD.json",
                            symbolspec_custom={"gold2": custom_file})
    assert rec["ok"], rec["not_built"]
    for rel, src in ((og.symbolspec_import_rel("gold2"),
                      ev / "import_EURUSD.G2.json"),
                     (og.tester_ini_rel("gold2", "m1_ohlc"),
                      ev / "tester_gold2_m1_ohlc.ini")):
        assert (pkg / rel).read_bytes() == src.read_bytes()
        man = json.loads((pkg / og.LAYOUT["archive_manifest"]).read_text())
        assert man["artifacts"][rel] == s8p._sha(src)
    meta = json.loads((pkg / og.LAYOUT["compile_metadata"]).read_text())
    assert meta["TERMINAL_BUILD"] == 5430
    assert "TerminalInfoInteger(TERMINAL_BUILD)" in \
        meta["TERMINAL_BUILD_SOURCE"]
    assert "custom-symbol export" in meta["TERMINAL_BUILD_SOURCE"]
    recon = json.loads((pkg / "reconciliation/gold2.json").read_text())
    assert recon["fill_model"]["inputs"]["spread_points"] == 1.0
    # the verifier, end to end, on the package the builder wrote
    rep = og.verify_symbolspec(pkg, FROZEN_SPEC, ["gold2"])
    assert rep["field_classes"]["name"] == og.EXACT_MATCH
    assert rep["field_classes"]["tick_value_profit"] == \
        og.DERIVED_EXACT_MATCH
    assert og.verify_compile(pkg, "x")["checks"]["provenance_fields"] \
        == "VALID"


def test_custom_export_without_fixed_spread_falls_back_with_reason():
    fill, note = s8p.fill_spec_of(
        json.loads((REPO / "artifacts/gold_2/manifest.json").read_text()),
        dict(CUSTOM_EXPORT, spread_points=2))
    assert fill["spread_points"] == 1.0        # manifest, never live 2
    assert "spread_source" not in fill
    assert "never used for a custom symbol" in note


# ------------------------------------------------ 6. S8-ANCHOR-REL-1

def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True,
                          capture_output=True, text=True).stdout.strip()


@pytest.fixture()
def anchored(tmp_path):
    """A throwaway repo: the frozen files at the anchor, a descendant that
    changes only an unfrozen file, and the frozen record pinning them."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@example.invalid")
    _git(repo, "config", "user.name", "t")
    _git(repo, "config", "commit.gpgsign", "false")
    files = {"artifacts/gold/gold_fixture.csv": "a\n",
             "artifacts/gold/manifest.json": "{}\n",
             "artifacts/gold_2/gold2_fixture.csv": "b\n",
             "artifacts/gold_2/reconciliation.json": "[]\n",
             "README": "x\n"}
    for rel, text in files.items():
        (repo / rel).parent.mkdir(parents=True, exist_ok=True)
        (repo / rel).write_text(text)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "anchor")
    anchor = _git(repo, "rev-parse", "HEAD")

    def sha(rel):
        return hashlib.sha256((repo / rel).read_bytes()).hexdigest()
    frozen = {"source": {"commit": anchor},
              "gold_1": {"fixture_sha256": sha("artifacts/gold/gold_fixture.csv"),
                         "manifest_sha256": sha("artifacts/gold/manifest.json")},
              "gold_2": {"fixture_sha256": sha("artifacts/gold_2/gold2_fixture.csv"),
                         "artifact_hash_chain": {
                             "reconciliation.json":
                                 sha("artifacts/gold_2/reconciliation.json")}}}
    (repo / "README").write_text("y\n")
    _git(repo, "commit", "-qam", "descendant")
    return repo, anchor, _git(repo, "rev-parse", "HEAD"), frozen


def test_anchor_itself_is_exact(anchored):
    repo, anchor, _, frozen = anchored
    rel = og.anchor_relation(repo, anchor, anchor, frozen)
    assert rel["relation"] == og.ANCHOR_RELATION_EXACT


def test_descendant_with_identical_frozen_bytes_is_accepted(anchored):
    repo, anchor, head, frozen = anchored
    rel = og.anchor_relation(repo, anchor, head, frozen)
    assert rel["relation"] == og.ANCHOR_RELATION_DESCENDANT, rel["reasons"]
    assert len(rel["frozen_files"]) == 4
    assert all(v["pin"] == v["at_commit"]
               for v in rel["frozen_files"].values())
    acc = og.source_commit_relation(
        head, anchor, lambda c: og.anchor_relation(repo, anchor, c, frozen))
    assert acc["accepted"] is True
    assert acc["relation"] == "DESCENDANT_FROZEN_BYTES_IDENTICAL"


def test_descendant_that_changed_a_frozen_file_is_refused(anchored):
    repo, anchor, _, frozen = anchored
    (repo / "artifacts/gold_2/reconciliation.json").write_text("[1]\n")
    _git(repo, "commit", "-qam", "edit a frozen file")
    head = _git(repo, "rev-parse", "HEAD")
    rel = og.anchor_relation(repo, anchor, head, frozen)
    assert rel["relation"] is None
    assert any("reconciliation.json sha256" in r for r in rel["reasons"])


def test_working_tree_bytes_are_not_what_is_judged(anchored):
    """The verifier hashes the bytes AT the recorded commit (git show); a
    restored working-tree file cannot launder a committed change."""
    repo, anchor, _, frozen = anchored
    p = repo / "artifacts/gold/manifest.json"
    p.write_text('{"x": 1}\n')
    _git(repo, "commit", "-qam", "edit frozen manifest")
    head = _git(repo, "rev-parse", "HEAD")
    p.write_text("{}\n")                       # restored, uncommitted
    assert og.anchor_relation(repo, anchor, head, frozen)["relation"] is None


def test_older_diverged_unknown_and_short_commits_are_refused(anchored):
    repo, anchor, head, frozen = anchored
    # older: the recorded commit is an ANCESTOR of the anchor
    _git(repo, "checkout", "-q", anchor)
    older_frozen = dict(frozen, source={"commit": head})
    assert og.anchor_relation(repo, head, anchor, older_frozen)[
        "relation"] is None
    # diverged: a sibling of the descendant
    _git(repo, "checkout", "-qb", "side", anchor + "~0")
    (repo / "README").write_text("z\n")
    _git(repo, "commit", "-qam", "sibling")
    sib = _git(repo, "rev-parse", "HEAD")
    assert og.anchor_relation(repo, head, sib, frozen)["relation"] is None
    # unknown commit, short SHA, no repository
    unknown = og.anchor_relation(repo, anchor, "f" * 40, frozen)
    assert unknown["relation"] is None
    assert "not a commit in this repository" in unknown["reasons"][0]
    assert og.anchor_relation(repo, anchor, head[:12], frozen)[
        "relation"] is None
    assert og.anchor_relation(None, anchor, head, frozen)["relation"] is None
    # no repository bound: only equality
    assert og.source_commit_relation(head, anchor)["accepted"] is False


def test_verify_compile_accepts_only_through_the_relation(tmp_path,
                                                          anchored):
    repo, anchor, head, frozen = anchored
    root = tmp_path / "pkg"
    (root / "compile").mkdir(parents=True)
    (root / og.LAYOUT["compile_log"]).write_text("0 errors, 0 warnings\n")
    (root / og.LAYOUT["ex5"]).write_bytes(b"ex5")
    meta = {"SOURCE_COMMIT": head, "COMPILER_VERSION": "5", "TERMINAL_BUILD":
            5430, "EX5_SHA256": og.sha256_file(root / og.LAYOUT["ex5"]),
            "COMPILE_TIMESTAMP": "2026-10-05T00:00:00Z",
            "COMPILER_LOG_SHA256": og.sha256_file(
                root / og.LAYOUT["compile_log"]),
            "ERRORS": 0, "WARNINGS": 0}
    (root / og.LAYOUT["compile_metadata"]).write_text(json.dumps(meta))
    plain = og.verify_compile(root, anchor)
    assert plain["checks"]["source_commit"] == og.MISMATCHED
    rel = og.verify_compile(
        root, anchor, lambda c: og.anchor_relation(repo, anchor, c, frozen))
    assert rel["checks"]["source_commit"] == "VALID"
    assert rel["source_commit_relation"]["relation"] == \
        og.ANCHOR_RELATION_DESCENDANT


def test_stage0_and_the_relation_read_the_same_pin_list():
    frozen = json.loads((REPO / gs.FROZEN_REL).read_text())
    pins = og.frozen_file_pins(frozen)
    assert {rel for rel, _, _ in pins} >= {
        "artifacts/gold/gold_fixture.csv", "artifacts/gold/manifest.json",
        "artifacts/gold_2/gold2_fixture.csv", "artifacts/gold_2/manifest.json"}
    assert gs.verify_frozen_hashes(REPO, frozen)["ok"] is True
