"""Tests for mql5bot.mt5tester — headless MT5 tester core (Phase 2).

Pure-Python surface (preset round-trips, ini generation, report parsing,
determinism validation) is fully covered here with no terminal required.
The Windows launch boundary is only tested for its guard behaviour.
"""

import pytest
from mql5bot.mt5tester import (
    EA_INPUT_DEFAULTS,
    MT5_MODEL_LABELS,
    MT5_TIMEFRAMES,
    RunSettings,
    inputs_to_lines,
    mt5_value_str,
    parse_report_html,
    parse_set,
    render_set,
    run_backtest,
    validate_inputs,
)
from mql5bot.mt5tester import (
    TesterConfig as MT5TesterConfig,
)

# ---------------------------------------------------------------------------
# .set presets
# ---------------------------------------------------------------------------


def test_mt5_value_str_formats():
    assert mt5_value_str(True) == "true"
    assert mt5_value_str(False) == "false"
    assert mt5_value_str(0) == "0"
    assert mt5_value_str(20240904) == "20240904"
    assert mt5_value_str(1.0) == "1.0"
    assert mt5_value_str(10.0) == "10.0"
    assert mt5_value_str(2.5) == "2.5"
    assert mt5_value_str(0.01) == "0.01"
    assert mt5_value_str("x=1") == "x=1"


def test_parse_set_roundtrip_real_preset():
    text = ("; mql5bot preset\n"
            "InpStrategy=0\n"
            "InpSlAtr=2.5\n"
            "InpAllowShort=true\n")
    lines = parse_set(text)
    assert [ln.key for ln in lines] == ["InpStrategy", "InpSlAtr", "InpAllowShort"]
    assert render_set(lines) == ("InpStrategy=0\n"
                                 "InpSlAtr=2.5\n"
                                 "InpAllowShort=true\n")


def test_parse_set_preserves_optimization_ranges():
    text = ("StopLoss=50||50||1||200||N\n"
            "TakeProfit=100||100||1||500||Y\n"
            "UseFilter=true\n")
    lines = parse_set(text)
    assert lines[0].value == "50"
    assert lines[0].opt_range == "||50||1||200||N"
    assert lines[1].opt_range == "||100||1||500||Y"
    assert lines[2].opt_range is None
    assert render_set(lines) == text


def test_parse_set_drops_comments_and_blanks():
    lines = parse_set("; comment\n\nInpMagic=1\n; tail\n")
    assert len(lines) == 1 and lines[0].key == "InpMagic"


def test_validate_inputs_rejects_unknown():
    with pytest.raises(ValueError, match="unknown EA input"):
        validate_inputs({"InpStrategy": 0, "InpNotReal": 1},
                        known=set(EA_INPUT_DEFAULTS))
    validate_inputs({"InpStrategy": 0}, known=set(EA_INPUT_DEFAULTS))
    validate_inputs({"Anything": 1}, known=None)  # third-party EA passthrough


def test_inputs_to_lines_renders_all_defaults():
    lines = inputs_to_lines(dict(EA_INPUT_DEFAULTS))
    assert len(lines) == len(EA_INPUT_DEFAULTS)
    by_key = {ln.key: ln.value for ln in lines}
    assert by_key["InpAllowShort"] == "true"
    assert by_key["InpStrategy"] == "0"
    assert by_key["InpRiskPercent"] == "1.0"


# ---------------------------------------------------------------------------
# Tester config + ini
# ---------------------------------------------------------------------------


def test_tester_config_defaults_valid():
    cfg = MT5TesterConfig()
    cfg.validate()
    assert cfg.timeframe in MT5_TIMEFRAMES
    assert cfg.model in MT5_MODEL_LABELS


@pytest.mark.parametrize("field,value,match", [
    ("timeframe", "H2", "timeframe"),
    ("model", 9, "model"),
    ("date_from", "2024/01/01", "YYYY.MM.DD"),
    ("date_from", "2025.01.01", "after"),  # later than the default date_to
    ("deposit", 0.0, "deposit"),
    ("currency", "US", "3-letter"),
    ("leverage", 0, "leverage"),
    ("ea", "Mql5Bot.mq5", ".ex5"),
])
def test_tester_config_rejects_bad_values(field, value, match):
    cfg = MT5TesterConfig()
    setattr(cfg, field, value)
    with pytest.raises(ValueError, match=match):
        cfg.validate()


def test_render_ini_golden():
    cfg = MT5TesterConfig(ea="Experts\\Mql5Bot\\Mql5Bot.ex5",
                       symbol="EURUSD", timeframe="H1", model=1,
                       date_from="2023.01.01", date_to="2024.01.01",
                       deposit=10000.0, currency="USD", leverage=100,
                       inputs={"InpStrategy": 0, "InpSlAtr": 2.5,
                               "InpAllowShort": True})
    ini = cfg.render_ini()
    assert ini.startswith("; generated by")
    assert "[Tester]" in ini and "[TesterInputs]" in ini
    assert ini.index("[Tester]") < ini.index("[TesterInputs]")
    for expected in ("Expert=Experts\\Mql5Bot\\Mql5Bot.ex5",
                     "Symbol=EURUSD", "Period=H1", "Model=1",
                     "Optimization=0", "FromDate=2023.01.01",
                     "ToDate=2024.01.01", "Deposit=10000.00",
                     "Currency=USD", "Leverage=100",
                     "ShutdownTerminal=1", "ReplaceReport=1",
                     "InpStrategy=0", "InpSlAtr=2.5", "InpAllowShort=true"):
        assert expected in ini, expected


def test_safe_report_name_deterministic_and_sanitized():
    a = MT5TesterConfig(symbol="XAUUSD", timeframe="H4",
                     date_from="2020.01.01", date_to="2021.06.30")
    b = MT5TesterConfig(symbol="XAUUSD", timeframe="H4",
                     date_from="2020.01.01", date_to="2021.06.30")
    assert a.safe_report_name == b.safe_report_name == "XAUUSD_H4_20200101_20210630"
    custom = MT5TesterConfig(report_name="My EA:run #1")
    assert custom.safe_report_name == "My_EA_run_1"
    with pytest.raises(ValueError, match="not usable"):
        _ = MT5TesterConfig(report_name="///").safe_report_name


# ---------------------------------------------------------------------------
# HTML report parsing
# ---------------------------------------------------------------------------

_REPORT_FIXTURE = """<!DOCTYPE html>
<html><head><style>.x{color:red}</style></head><body>
<table class="report">
<tr><td>Strategy Test report</td></tr>
<tr><td>Demo-Broker (Build 4401)</td></tr>
<tr><td>Expert Advisor:</td><td>Mql5Bot</td></tr>
<tr><td>Symbol:</td><td>EURUSD (Euro vs US Dollar)</td></tr>
<tr><td>Period:</td><td>H1 (2023.01.01 - 2024.01.01)</td></tr>
<tr><td>Parameters:</td><td>InpStrategy=0</td></tr>
<tr><td></td><td>InpSlAtr=2.5</td></tr>
<tr><td>Initial Deposit:</td><td>10 000.00 USD</td></tr>
<tr><td>Leverage:</td><td>1:100</td></tr>
</table>
<table>
<tr><td>History Quality</td><td>99%</td></tr>
<tr><td>Bars</td><td>6 234</td></tr>
<tr><td>Ticks</td><td>1 200 000</td></tr>
<tr><td>Total Net Profit</td><td>1 234.56</td></tr>
<tr><td>Gross Profit</td><td>3 456.78</td></tr>
<tr><td>Gross Loss</td><td>-2 222.22</td></tr>
<tr><td>Profit Factor</td><td>1.56</td></tr>
<tr><td>Expected Payoff</td><td>9.15</td></tr>
<tr><td>Balance Drawdown Absolute</td><td>0.00</td></tr>
<tr><td>Balance Drawdown Maximal</td><td>949.00 (10.79%)</td></tr>
<tr><td>Balance Drawdown Relative</td><td>10.93% (756.00)</td></tr>
<tr><td>Recovery Factor</td><td>1.30</td></tr>
<tr><td>Total Trades</td><td>135</td></tr>
<tr><td>Total Deals</td><td>270</td></tr>
<tr><td>Short Trades (won %)</td><td>60 (100.00%)</td></tr>
<tr><td>Long Trades (won %)</td><td>75 (52.00%)</td></tr>
<tr><td>Profit Trades (% of total)</td><td>100 (74.07%)</td></tr>
<tr><td>Loss Trades (% of total)</td><td>35 (25.93%)</td></tr>
<tr><td>Largest profit trade</td><td>120.40</td></tr>
<tr><td>Largest loss trade</td><td>-45.10</td></tr>
<tr><td>Average profit trade</td><td>34.57</td></tr>
<tr><td>Average loss trade</td><td>-63.49</td></tr>
<tr><td>Maximum consecutive wins</td><td>8 (450.10)</td></tr>
<tr><td>Maximum consecutive losses</td><td>3 (-200.00)</td></tr>
<tr><td>OnTester result</td><td>2.71</td></tr>
</table>
<script>var noise = "Total Net Profit 999";</script>
</body></html>"""


def test_parse_report_html_canonical_metrics():
    rep = parse_report_html(_REPORT_FIXTURE)
    m = rep.metrics
    assert m["total_net_profit"] == 1234.56
    assert m["gross_profit"] == 3456.78
    assert m["gross_loss"] == -2222.22
    assert m["profit_factor"] == 1.56
    assert m["expected_payoff"] == 9.15
    assert m["balance_drawdown_absolute"] == 0.0
    assert m["balance_drawdown_maximal"] == {"money": 949.0, "pct": 10.79}
    assert m["balance_drawdown_relative"] == {"pct": 10.93, "money": 756.0}
    assert m["recovery_factor"] == 1.30
    assert m["total_trades"] == 135
    assert m["total_deals"] == 270
    assert m["short_trades_won_pct"] == {"count": 60, "pct": 100.0}
    assert m["long_trades_won_pct"] == {"count": 75, "pct": 52.0}
    assert m["profit_trades_pct"] == {"count": 100, "pct": 74.07}
    assert m["loss_trades_pct"] == {"count": 35, "pct": 25.93}
    assert m["largest_profit_trade"] == 120.40
    assert m["largest_loss_trade"] == -45.10
    assert m["average_profit_trade"] == 34.57
    assert m["average_loss_trade"] == -63.49
    assert m["max_consecutive_wins"] == {"count": 8, "money": 450.10}
    assert m["max_consecutive_losses"] == {"count": 3, "money": -200.0}
    assert m["on_tester_result"] == "2.71"


def test_parse_report_html_settings_and_fields():
    rep = parse_report_html(_REPORT_FIXTURE)
    assert rep.settings["expert"] == "Mql5Bot"
    assert rep.settings["symbol"] == "EURUSD (Euro vs US Dollar)"
    assert rep.settings["period"] == "H1 (2023.01.01 - 2024.01.01)"
    assert rep.settings["deposit"] == "10 000.00 USD"
    assert rep.settings["leverage"] == "1:100"
    # every label/value pair preserved verbatim, including unknown rows
    assert rep.fields["Symbol:"] == "EURUSD (Euro vs US Dollar)"
    assert rep.fields["OnTester result"] == "2.71"
    assert "Parameters:" in rep.fields
    assert rep.tables >= 2


def test_parse_report_html_missing_rows_are_none_and_script_ignored():
    html = ("<html><table>"
            "<tr><td>Total Net Profit</td><td>5.00</td></tr>"
            "</table>"
            "<script>var x = '<tr><td>Total Net Profit</td><td>999</td></tr>';</script>"
            "</html>")
    rep = parse_report_html(html)
    assert rep.metrics["total_net_profit"] == 5.0
    assert rep.metrics["gross_profit"] is None
    assert rep.metrics["sharpe_ratio"] is None
    assert len(rep.fields) == 1


def test_parse_report_html_old_style_drawdown_labels():
    html = ("<html><table>"
            "<tr><td>Absolute Drawdown</td><td>405.00</td></tr>"
            "<tr><td>Maximal Drawdown</td><td>949.00 (10.79%)</td></tr>"
            "<tr><td>Relative Drawdown</td><td>10.93% (756.00)</td></tr>"
            "</table></html>")
    m = parse_report_html(html).metrics
    assert m["balance_drawdown_absolute"] == 405.0
    assert m["balance_drawdown_maximal"] == {"money": 949.0, "pct": 10.79}
    assert m["balance_drawdown_relative"] == {"pct": 10.93, "money": 756.0}


def test_parse_report_html_case_and_whitespace_tolerance():
    html = ("<html><table>"
            "<tr><td>  total&nbsp;&nbsp;NET&nbsp;profit </td><td> 42.50 </td></tr>"
            "</table></html>")
    rep = parse_report_html(html)
    assert rep.metrics["total_net_profit"] == 42.5
    # raw label kept verbatim (cleaned) in fields
    assert "total NET profit" in rep.fields


# ---------------------------------------------------------------------------
# runner guard
# ---------------------------------------------------------------------------


def test_run_backtest_guard_off_windows():
    cfg = MT5TesterConfig()
    settings = RunSettings(terminal_dir="C:\\MT5", data_folder="C:\\MT5")
    with pytest.raises(RuntimeError, match="Windows-only"):
        run_backtest(cfg, settings)
